[package]
name = "files-to-prompt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
glob = "0.3"
regex = "1"
walkdir = "2"
lazy_static = "1"
colored = "2.2.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
tempfile = "3"

